[files]
data = "./data/mimic_discharge_summaries_bert_128tkns.pt"
labels = "./data/mimic_30d_readmit_labels.pt"

[train]
random_seed = 42
correct_imbalance = true
batch_size = 128
num_epochs = 5
embedding_size = 768
num_filters = 64
dropout = 0.5
lr = 0.001
